### ISSUE TITLE
Upgrade.sls aborts with error

### ISSUE THREAD

**Issue by aanjaneyam** [saltstack-formulas/apt-formula#13]
When I run update.sls and upgrade.sls through highstate run. 
`----------
          ID: apt-get update
    Function: cmd.run
      Result: True
     Comment: Command "apt-get update" run
     Started: 14:55:03.296087
    Duration: 7082.109 ms
     Changes:  
              ----------
              pid:
                  21886
              retcode:
                  0
              stderr:
              stdout:
                  Hit http://security.debian.org jessie/updates InRelease
                  Hit http://security.debian.org jessie/updates/main amd64 Packages
                  Hit http://security.debian.org jessie/updates/main Translation-en
                  Ign http://http.debian.net jessie InRelease
                  Hit http://http.debian.net jessie-backports InRelease
                  Hit http://repo.saltstack.com jessie InRelease
                  Ign http://httpredir.debian.org jessie InRelease
                  Hit http://http.debian.net jessie Release.gpg
                  Hit http://repo.saltstack.com jessie/main amd64 Packages
                  Get:1 http://http.debian.net jessie-backports/main Sources/DiffIndex [27.8 kB]
                  Hit http://httpredir.debian.org jessie-updates InRelease
                  Get:2 http://http.debian.net jessie-backports/main amd64 Packages/DiffIndex [27.8 kB]
                  Hit http://httpredir.debian.org jessie-backports InRelease
                  Get:3 http://http.debian.net jessie-backports/main Translation-en/DiffIndex [27.4 kB]
                  Hit http://httpredir.debian.org jessie Release.gpg
                  Ign http://repo.saltstack.com jessie/main Translation-en
                  Hit http://http.debian.net jessie Release
                  Get:4 http://httpredir.debian.org jessie-updates/main amd64 Packages/DiffIndex [1012 B]
                  Hit http://http.debian.net jessie/main Sources
                  Get:5 http://httpredir.debian.org jessie-updates/main Translation-en/DiffIndex [736 B]
                  Hit http://http.debian.net jessie/main amd64 Packages
                  Hit http://http.debian.net jessie/main Translation-en
                  Get:6 http://httpredir.debian.org jessie-backports/main Sources/DiffIndex [27.8 kB]
                  Get:7 http://httpredir.debian.org jessie-backports/main amd64 Packages/DiffIndex [27.8 kB]
                  Get:8 http://httpredir.debian.org jessie-backports/main Translation-en/DiffIndex [27.4 kB]
                  Hit http://httpredir.debian.org jessie Release
                  Hit http://httpredir.debian.org jessie/main amd64 Packages
                  Hit http://httpredir.debian.org jessie/main Translation-en
                  Fetched 168 kB in 3s (45.7 kB/s)
##                   Reading package lists...

```
      ID: apt-get upgrade
Function: cmd.run
  Result: False
 Comment: Command "apt-get upgrade" run
 Started: 14:55:10.378360
Duration: 268.491 ms
 Changes:   
          ----------
          pid:
              21941
          retcode:
              1
          stderr:
          stdout:
              Reading package lists...
              Building dependency tree...
              Reading state information...
              The following packages will be upgraded:
                libdns-export100 libirs-export91 libisc-export95 libisccfg-export90
                linux-image-3.16.0-4-amd64 python-requests python-urllib3
              7 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
              Need to get 34.6 MB of archives.
              After this operation, 204 kB disk space will be freed.
              Do you want to continue? [Y/n] Abort.
```
## Summary

Succeeded: 1 (changed=2)
## Failed:    1

Total states run:     2
ERROR: Minions returned with non-zero exit code
`

**Comment by gravyboat** [comment]
The upgrade state is extremely simplistic. It's failing because there is a prompt to complete the upgrade.

**Comment by aanjaneyam** [comment]
how to insert the -y option. What happens if I changed the upgrade.sls file to

`apt-get -y upgrade:
  cmd:
    - run`

**Comment by gravyboat** [comment]
Should work fine.

**Comment by aanriot** [comment]
Can we close the issue @aanjaneyam ?
