### ISSUE TITLE
Handle apt.conf.d configuration with pillars like preferences.d

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack-formulas/apt-formula#29]
the preferences.d files shipped via the pillars are quite nice, it would be nice to be able to do the same with apt.conf.d

**Comment by aboe76** [comment]
@arthurlogilab something like https://github.com/saltstack-formulas/apt-formula/pull/17
but no progress...

**Comment by aanriot** [comment]
Added in #38 .
